// Barrel export for all shared types
export type {
  // Analytics types
  Goal,
  GoalFormData,
  AnalyticsEvent,
  Session,
  PageView,
  SessionEvent,
  SessionDetail,
  ErrorItem,
  ErrorStatusEntry,
  ErrorStatuses,
  StatusCounts,
  SeverityCounts,
  Funnel,
  FunnelAnalysisStep,
  FunnelAnalysis,
  Vital,
  BudgetViolation,
  FlowPage,
  FlowLink,
  FlowData,
  LiveActivity,
  Insight,
  ComparisonStats,
  Referrer,
  ApiKey,
  Alert,
  EmailReport,
  UptimeMonitor,
  TeamMember,
  Webhook,
  PerfBudget,
  SiteSettings,
} from './analytics'

export type {
  // Dashboard UI types
  ModalOptions,
  ModalAPI,
  GoalModalAPI,
  NavTab,
  DashboardHeaderAPI,
  DateRange,
  ControlsBarAPI,
  ReferrersTableProps,
} from './dashboard'

export type {
  // API response types
  GoalsResponse,
  EventsResponse,
  SessionsResponse,
  ErrorsResponse,
  ErrorStatusesResponse,
  FunnelsResponse,
  VitalsResponse,
  BudgetViolationsResponse,
  FlowResponse,
  LiveResponse,
  InsightsResponse,
  ComparisonResponse,
  ReferrersResponse,
  ApiKeysResponse,
  AlertsResponse,
  EmailReportsResponse,
  UptimeResponse,
  TeamResponse,
  WebhooksResponse,
  PerfBudgetsResponse,
  RetentionResponse,
} from './api'
