// DynamoDB Utilities
export {
  buildGSI1PK,
  buildPeriodSK,
  buildPK,
  buildSiteQuery,
  buildSK,
  buildTimeRangeQuery,
  buildTimestampKey,
  determinePeriod,
  fromDynamoValue,
  generateId,
  generateSessionId,
  getDailySalt,
  getPeriodStart,
  hashVisitorId,
  KeyPatterns,
  marshal,
  toDynamoValue,
  unmarshal,
} from './dynamodb'

// Configuration
export {
  defaultAnalyticsConfig,
  defaultConfig,
  defaultGSIs,
  defaultSingleTableConfig,
  defineConfig,
  getConfig,
  getTableConfig,
  getTtlForEntity,
  resetConfig,
  setConfig,
  type AnalyticsConfig,
  type UserAnalyticsConfig,
} from './config'

export {
  // Types
  type AggregatedStats,
  type AggregationJobStatus,
  type AggregationPeriod,
  AggregationPipeline,
  type AggregatorOptions,
  AnalyticsAggregator,
  AnalyticsKeyPatterns,
  AnalyticsQueryAPI,
  AnalyticsStore,
  type AnalyticsStoreOptions,
  type CampaignStats,
  type Conversion,
  type CustomEvent,
  type DashboardData,
  type DashboardSummary,
  type DateRange,
  type DeviceStats,
  type DeviceType,
  type EventStats,
  generateTrackingScript,
  type GeoStats,
  type Goal,
  GoalMatcher,
  type GoalMatchResult,
  type GoalPerformance,
  type GoalStats,
  type GoalType,
  type PageStats,
  type PageView,
  type PipelineJobConfig,
  type PipelineJobResult,
  type QueryOptions,
  type RealtimeData,
  type RealtimeStats,
  type ReferrerStats,
  type Session,
  type Site,
  type SiteSettings,
  type TimeSeriesPoint,
  type TopItem,
  type TrackingScriptOptions,
} from './Analytics'

// API Handlers
export {
  AnalyticsAPI,
  type AnalyticsAPIConfig,
  type AnalyticsRequest,
  type AnalyticsResponse,
  type CollectPayload,
  createBunRouter,
  createLambdaHandler,
  type HandlerContext,
  type SessionStore,
} from './api'

// Dashboard UI Components
export {
  // Types
  type AnalyticsApiConfig,
  // Composables
  AnalyticsClient,
  // Components
  AnalyticsDashboard,
  // Utilities
  calculateAxisTicks,
  calculateChange,
  calculatePercentageChange,
  type ChartProps,
  createAnalyticsComposable,
  createRealtimePoller,
  darkTheme,
  type DashboardTheme,
  DateRangePicker,
  type DateRangePreset,
  dateRangePresets,
  // Theme
  defaultTheme,
  DeviceBreakdown,
  fetchDashboardData,
  formatCompact,
  formatDate,
  formatDateRange,
  formatDuration,
  formatNumber,
  formatPercentage,
  getDateRangeFromPreset,
  getDateRangePreset,
  RealtimeCounter,
  type RealtimeCounterProps,
  StatCard,
  type StatCardProps,
  TimeSeriesChart,
  type TimeSeriesDataPoint,
  TopList,
  type TopListProps,
  useAnalytics,
} from './dashboard'

// Infrastructure (CloudFormation, CDK, Setup)
export {
  type AnalyticsApiProps,
  type AnalyticsTableProps,
  checkTableStatus,
  type CloudFormationConfig,
  createAnalyticsTable,
  createPitrMigration,
  createStreamsMigration,
  createTimeBasedGsiMigration,
  type DynamoDBClientLike,
  enableTtl,
  generateAwsCliCommands,
  generateCdkCode,
  generateCdkTableCode,
  generateCloudFormationJson,
  generateCloudFormationTemplate,
  generateCloudFormationYaml,
  generateCreateTableInput,
  generateSamTemplate,
  generateSamYaml,
  type MigrationResult,
  type MigrationStep,
  printSetupInstructions,
  runMigrations,
  type SetupConfig,
  type SetupResult,
} from './infrastructure'

// Model Connector (Single-Table Design Integration)
export {
  type AccessPattern,
  analyticsModelRegistry,
  type EntityDesign,
  generateAccessPatternMatrix,
  generateAnalyticsDesignDoc,
  generateAnalyticsSingleTableDesign,
  getAllAnalyticsModels,
  getAnalyticsModel,
  getAnalyticsModelNames,
  type SingleTableDesign,
  type StacksModelDefinition,
} from './model-connector'

// Stacks Model Definitions
export {
  AggregatedStatsModel,
  type AnalyticsModelName,
  analyticsModels,
  CampaignStatsModel,
  ConversionModel,
  CustomEventModel,
  DeviceStatsModel,
  EventStatsModel,
  GeoStatsModel,
  GoalModel,
  GoalStatsModel,
  PageStatsModel,
  PageViewModel,
  RealtimeStatsModel,
  ReferrerStatsModel,
  SessionModel,
  SiteModel,
} from './models'

// Stacks Integration
export {
  createAnalyticsDriver,
  createAnalyticsMiddleware,
  createDashboardActions,
  createServerTrackingMiddleware,
  type DynamoDBAnalyticsConfig,
  DynamoDBAnalyticsDriver,
  type StacksAnalyticsOptions,
} from './stacks-integration'
